### PR TITLE
Add a layout to the generate mesh form

### PR DESCRIPTION
**Pull request by m-kuhn**

### CODE REVIEW

**Comment by m-kuhn** [comment]
Is it worth something? Didn't even remember when I did that and what it is :)

**Comment by saberraz** [comment]
Not sure...trying to port it to QGIS 2.x or we can wait and do it once for QGIS 3.x :)

**Comment by m-kuhn** [comment]
Wow, you are going to support QGIS 3!

**Comment by saberraz** [comment]
Someone should start it..maybe we should ask the PSC or dev list when qgis 3.0 is out :)

**Pull request merged**
